# Generated by Django 6.0.4 on 2026-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superAdmin', 'Super Admin'), ('clientUser', 'Patient'), ('adminUser', 'Facility Admin')], default='clientUser', max_length=20),
        ),
    ]
