# Generated by Django 6.0.2 on 2026-05-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='company_categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.category'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='company_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
