# Generated by Django 6.0.2 on 2026-05-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_company_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='company_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.category'),
        ),
    ]
