# Generated by Django 6.0.4 on 2026-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_company_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='company_logo',
            field=models.ImageField(blank=True, default='facility_logos/default.png', null=True, upload_to='facility_logos/'),
        ),
    ]
