# Generated by Django 6.0.4 on 2026-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_company_logo'),
        ('services_app', '0004_remove_service_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='languages',
        ),
        migrations.AddField(
            model_name='facility',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
