# Generated by Django 6.0.4 on 2026-07-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='languages',
        ),
    ]
