# Generated by Django 6.0.4 on 2026-06-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
